# Generated by Django 2.0.13 on 2019-07-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='uploads/%Y/%m/%d/', width_field=100),
        ),
    ]
