# Generated by Django 2.0.13 on 2019-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190701_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='link img'),
        ),
    ]
