# Generated by Django 2.0.13 on 2019-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190701_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='link img'),
        ),
    ]
