# Generated by Django 2.2.3 on 2019-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190710_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Only webm or mp4', null=True, upload_to='media/%Y/%m/%d/', verbose_name='video'),
        ),
    ]
