# Generated by Django 2.2.3 on 2019-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190713_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(blank=True, help_text='Only webm or mp4', null=True, upload_to='media/%Y/%m/%d', verbose_name='video'),
        ),
    ]
