# Generated by Django 2.2.3 on 2019-07-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190713_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='feed',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(to='blog.PostFile'),
        ),
    ]
