# Generated by Django 2.2.3 on 2019-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190713_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Only webm or mp4', null=True, upload_to='media/%Y/%m/%d/', verbose_name='video'),
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
